version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/modules/jooby-graphiql"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/modules/jooby-graphql-playground"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: graphql-playground-react
    versions:
    - "> 1.7.26, < 1.8"
- package-ecosystem: npm
  directory: "/modules/jooby-redoc"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redoc
    versions:
    - 2.0.0-rc.51
- package-ecosystem: npm
  directory: "/modules/jooby-swagger-ui"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: swagger-ui-dist
    versions:
    - 3.42.0
    - 3.43.0
    - 3.45.0
    - 3.45.1
