language: java

before_install:
  - export MAVEN_OPTS=-Xmx1024m

script:
  - ./build/travis.sh

jdk:
  - oraclejdk8

branches:
  only:
    - master

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./build/snapshot.sh
  
